name: blip2-serving
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - huggingface_hub
      - pillow
      - azure-storage-blob
      - accelerate
      - ftfy
      - safetensors
      - tokenizers
      - requests