import { StyleSheet } from 'react-native';

const shadow = {
  shadowColor: 'black',
  shadowOffset: { width: 10, height: 10 },
  shadowOpacity: 0.8,
  shadowRadius: 20,
  elevation: 7,
};

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#F9F9F9",
    paddingTop: 70,
    paddingLeft: 25,
    paddingRight: 25,
    height: '100%',
  },
  title: {
    fontSize: 24,
    color: "#436D9D",
    fontFamily: 'PretendardGOV-ExtraBold',
    marginBottom: 25,
  },
  subtitle: {
    fontSize: 17,
    color: "#436D9D",
    fontFamily: 'PretendardGOV-Bold',
    marginBottom: 15,
  },
  photoBox: {
    backgroundColor: "#ECECEC",
    height: 180,
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderColor: "#748ca7ff",
    borderWidth: 1,
    ...shadow,
  },
  plusIcon: {
    fontSize: 40,
    fontFamily: 'PretendardGOV-Bold',
    color: "black",
  },
  photo: {
    width: "90%",
    height: "80%",
    borderRadius: 20,
    resizeMode: 'cover',
  },
  input: {
    backgroundColor: "#ddd",
    borderRadius: 10,
    height: 50,
    paddingHorizontal: 15,
    marginBottom: 20,
    color: "#000",
  },
  submitButton: {
    backgroundColor: "#436D9D",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
    ...shadow,
  },
  chooseButton: {
    backgroundColor: "#436D9D",
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: "flex-start",
    paddingLeft: 15,
    marginBottom: 20,
    ...shadow,
  },
  submitText: {
    fontSize: 17,
    color: "white",
    fontFamily: 'PretendardGOV-Bold',
  },
  viewStyle: {
    backgroundColor: "#436D9D",
    borderRadius: 20,
    height: 200,
    marginBottom: 20,
    padding: 20,
    paddingTop: 20,
    ...shadow,
  },
  viewTitle: {
    fontSize: 17,
    color: "white",
    fontFamily: 'PretendardGOV-Bold',
    marginBottom: 10,
  },
  textArea: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    height: 130,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginBottom: 15,
    color: "#000",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    maxHeight: '100%',
  },
  modalContent: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 12,
    elevation: 10,
    height: '70%',
  },
  modalButton: {
    backgroundColor: "#436D9D",
    borderRadius: 20,
    marginTop: 10,
    height: 35,
    alignItems: 'center',
    paddingVertical: 4,
    ...shadow,
  },
  recordButton: {
      backgroundColor: "#CBCDD3",
      borderRadius: 20,
      width: 170,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
      display: "flex",
      flexDirection: "row",
      borderColor: "white",
      borderWidth: 1,
      marginBottom: 20,
      // ...shadow,
  },
  recordIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    marginRight: 5,
  },
  recordText: {
    color: 'black',
    fontSize: 14,
    fontWeight: 'bold',
  },
  locationAddressText: {
    height: 80,
    width: '100%',
    backgroundColor: "#ECECEC",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#436D9D",
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginTop: 10,
    marginBottom: 10,
    alignSelf: 'center',
    textAlign: 'center',
    color: "black",
    fontSize: 16,
    fontWeight: 'bold',
    ...shadow,
  },

  micButton: {
    width: 200,
    height: 200,
    backgroundColor: "#7ED8C2",
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 20,
  },
    micRecordingButton: {
    width: 200,
    height: 200,
    backgroundColor: "#07ef60ff",
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 20,
  },

  voiceDescription: {
    textAlign:'center',
    fontSize: 22,
    color: "black",
    fontFamily: 'PretendardGOV-Bold',
    marginBottom: 10,
    },

    voiceModal: {
      backgroundColor: 'white',
      borderRadius: 16,
      padding: 24,
      width: '80%',
      alignSelf: 'center',        
      alignItems: 'center',       
      justifyContent: 'center',   
    },
    voiceModalButton:{
    backgroundColor: "#E0E0E0",
    borderRadius: 20,
    marginTop: 100,
    width:200,
    height: 35,
    alignItems: 'center',
    paddingVertical: 4,
    
    },
    voiceModalText:{
      fontSize: 17,
      color: "black",
      fontFamily: 'PretendardGOV-Bold'
    }  
  });