import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
    paddingTop: 24,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
    marginBottom: 16,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  rank: {
    width: 32,
    fontWeight: 'bold',
    fontSize: 18,
    color: '#4A90E2',
    textAlign: 'center',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginHorizontal: 10,
    backgroundColor: '#eee',
  },
  nickname: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  score: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF9800',
    marginLeft: 8,
  },
  myInfoContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#e3e3e3',
    padding: 14,
    borderTopWidth: 1,
    borderColor: '#ccc',
    alignItems: 'center',
  },
  myRank: {
    fontWeight: 'bold',
    marginBottom: 6,
    fontSize: 16,
    color: '#4A90E2',
  },
});