import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
    paddingTop: 24,
  },
  title: {
    fontSize: 25,
    fontFamily: 'PretendardGOV-Bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 16,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  myItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 3,
    borderColor: '#4A90E2',
  },
  rank: {
    width: 32,
    fontFamily: 'PretendardGOV-Bold',
    fontSize: 18,
    color: '#4A90E2',
    textAlign: 'center',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginHorizontal: 10,
    backgroundColor: '#eee',
  },
  nickname: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    fontFamily: 'PretendardGOV-Bold',
    overflow: 'hidden',      // 말줄임표 처리를 위해 필요
    textOverflow: 'ellipsis', // 웹 스타일이지만 의미 전달용
    whiteSpace: 'nowrap',    // 웹에서 쓰는 방식 (RN에선 numberOfLines로 처리)
  },
  score: {
    fontSize: 17,
    color: '#FF9800',
    marginLeft: 8,
    fontFamily: 'PretendardGOV-ExtraBold',
    backgroundColor: '#ffffffff',
    height: 40,
    width: 100,
    textAlign: 'center',
    lineHeight: 40,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  myInfoContainer: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#87b6e7ff',
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
    paddingHorizontal: 30,
  },
  myRank: {
    width: 32,
    fontFamily: 'PretendardGOV-Bold',
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
  },
  myScore: {
    fontSize: 17,
    color: '#FF9800',
    marginLeft: 8,
    fontFamily: 'PretendardGOV-ExtraBold',
    backgroundColor: 'white',
    height: 40,
    width: 100,
    textAlign: 'center',
    lineHeight: 40,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
});